[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fib"
version = "0.1"
dependencies = []

[project.scripts]
fib = "fib:main"

[tool.isort]
profile = "black"