name: Run Tests

on:
  push:
    branches:
      - master
    paths:
      - "fib/**"
      - "tests/**"
  pull_request:
    branches:
      - master
    paths:
      - "fib/**"
      - "tests/**"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install . && pip install -r requirements_dev.txt

      - name: Run Flake8 linting
        run: flake8

      - name: Run tests
        run: pytest
